spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace